### PR TITLE
ScholarshipJobFixes

### PR DESCRIPTION
**Pull request by AcevedoC17**
Branch addressing issues #137, #138, #139

### CODE REVIEW

**Review by GabrielGranell15 — COMMENTED** [review]
Was Scholarship List moved to JobList?

**Comment by AcevedoC17** [comment]
JobList copies ScholarshipList Logic but renames default values

**Comment by GabrielGranell15** [comment]
Got it.

**Review by EdwinC1339 — APPROVED** [review]

**Review by EdwinC1339 — APPROVED** [review]
Approved

**Pull request merged**
