### PR TITLE
DataGrip .idea config

### PR DESCRIPTION
**Pull request by EdwinC1339**
Files created by DataGrip

### CODE REVIEW

**Comment by AcevedoC17** [comment]
Good work

**Review by AcevedoC17 — APPROVED** [review]
Looks good to me

**Comment by Robert-6** [comment]
Nice, looks good

**Review by Robert-6 — COMMENTED** [review]
Nice

**Review by Robert-6 — COMMENTED** [review]
Yep, Nice looks good

**Pull request merged**
